package com.example.cobolparser.dto;

/**
 * Represents the standard JSON response for API operations.
 * It includes a success flag, a message, and optionally a path to the output
 * generated by the operation (e.g., GCS path for the processed schema).
 */
public class ApiResponse {
    /**
     * Indicates whether the API operation was successful.
     * {@code true} for success, {@code false} for failure.
     */
    private boolean success;

    /**
     * A descriptive message about the outcome of the operation.
     * For success, it might be a confirmation. For failure, it provides error details.
     */
    private String message;

    /**
     * The Google Cloud Storage (GCS) path where the output of the operation
     * (e.g., the generated JSON schema) is stored.
     * This field may be null, especially in case of errors or if the operation
     * does not produce a file output.
     */
    private String outputGcsPath; // Can be null

    /**
     * Constructs an ApiResponse for a successful operation.
     *
     * @param success Should be {@code true}.
     * @param message A message describing the successful outcome.
     * @param outputGcsPath The GCS path to the generated output file.
     */
    public ApiResponse(boolean success, String message, String outputGcsPath) {
        this.success = success;
        this.message = message;
        this.outputGcsPath = outputGcsPath;
    }

    /**
     * Constructs an ApiResponse for a failed operation, or a successful operation
     * that does not produce a GCS output file.
     *
     * @param success Indicates if the operation was successful (can be {@code true} or {@code false}).
     * @param message A message describing the outcome or error.
     */
    public ApiResponse(boolean success, String message) {
        this.success = success;
        this.message = message;
        // outputGcsPath will be null by default
    }

    /**
     * Checks if the operation was successful.
     * @return {@code true} if successful, {@code false} otherwise.
     */
    public boolean isSuccess() {
        return success;
    }

    /**
     * Sets the success status of the operation.
     * @param success {@code true} for success, {@code false} for failure.
     */
    public void setSuccess(boolean success) {
        this.success = success;
    }

    /**
     * Gets the descriptive message.
     * @return The message string.
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the descriptive message.
     * @param message The message string.
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Gets the GCS path to the output file.
     * @return The GCS path string, or null if not applicable.
     */
    public String getOutputGcsPath() {
        return outputGcsPath;
    }

    /**
     * Sets the GCS path to the output file.
     * @param outputGcsPath The GCS path string.
     */
    public void setOutputGcsPath(String outputGcsPath) {
        this.outputGcsPath = outputGcsPath;
    }
}
